import React from 'react';
import { Image, Modal, Pressable, StyleSheet, View } from 'react-native';
import { IconButton, Label } from './ui';
export function ModelOffer({ onClose, onUpgrade }: {
    onClose: () => void;
    onUpgrade: () => void;
}) {
    return <Modal visible transparent animationType="fade" statusBarTranslucent onRequestClose={onClose}><View style={S.overlay}><Pressable accessibilityRole="button" accessibilityLabel="Dismiss model offer" onPress={onClose} style={StyleSheet.absoluteFill}/><View style={S.card}><Image source={require('../assets/model-v6-offer.png')} style={[StyleSheet.absoluteFill, { width: '100%', height: '100%' }]} resizeMode="cover"/><View style={S.top}><Label style={S.badge}>NEW MODEL</Label><IconButton name="close" label="Close model offer" onPress={onClose} style={S.close} size={28} color="#101012"/></View><View style={{ flex: 1 }}/><Label style={S.title}>There’s so much more{'\n'}to v6.</Label><Label style={S.description}>Upgrade for access to our premium v6 and v6-wild models.</Label><Pressable accessibilityRole="button" accessibilityLabel="Upgrade model access" onPress={onUpgrade} style={S.upgrade}><Label style={S.upgradeText}>Upgrade now</Label></Pressable></View></View></Modal>;
}
const S = StyleSheet.create({ overlay: { flex: 1, paddingHorizontal: 36, paddingVertical: 48, justifyContent: 'center', alignItems: 'center', backgroundColor: '#10101260' }, card: { width: '100%', maxWidth: 360, height: 520, maxHeight: '100%', borderRadius: 20, overflow: 'hidden', backgroundColor: '#000', padding: 28 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, badge: { fontSize: 14, lineHeight: 20, paddingHorizontal: 8, paddingVertical: 2, backgroundColor: '#FF399C', color: '#101012', borderRadius: 99 }, close: { backgroundColor: '#FFF', borderRadius: 99, width: 40, height: 40 }, title: { fontSize: 36, lineHeight: 38, fontFamily: 'InstrumentSerif', marginHorizontal: -16, color: '#FFF', textAlign: 'center' }, description: { fontSize: 16, lineHeight: 22, color: '#FFF', textAlign: 'center', marginTop: 18 }, upgrade: { marginTop: 18, height: 48, backgroundColor: '#FFF', paddingHorizontal: 20, borderRadius: 99, alignSelf: 'center', justifyContent: 'center' }, upgradeText: { fontSize: 18, lineHeight: 24, color: '#101012' } });
