import { ThemeColors, ThemedSurface, useTheme } from './Theme';
import React from 'react';
import { Image, Platform, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { AudioTrack } from './audioData';
import { useNotificationAccess } from './useNotificationAccess';
import { C, Icon, IconButton, Label } from './ui';
export function Notifications({ access, songs, onClose, onOpenSong, hooks = false, onCreate }: { hooks?: boolean; onCreate?: () => void; access: ReturnType<typeof useNotificationAccess>; songs: AudioTrack[]; onClose: () => void; onOpenSong: (track: AudioTrack) => void }) {
  const theme = useTheme(); const C = theme.colors; const N = styles(C);
  const banner = !hooks && !access.preferences.dismissed && access.access !== 'granted';
  return <ThemedSurface><View style={N.page}>
    <View style={N.header}><IconButton name="chevron-left" label="Back from notifications" onPress={onClose} style={N.back} /><Label style={N.title}>Notifications</Label></View>
    <ScrollView contentContainerStyle={N.content} showsVerticalScrollIndicator={false}>
      {banner && <View style={N.banner}><View style={N.bannerHeading}><Icon name="bell" size={24} /><Label style={N.bannerTitle}>Notifications Disabled</Label><IconButton name="close" label="Dismiss notification permission banner" disabled={!access.ready || access.busy} onPress={() => void access.dismiss()} style={N.close} /></View><View style={N.bannerBody}><Label style={N.description}>Get notified so you never miss out when you receive a new like, comment, follow, share, or release on Suno.</Label><Pressable accessibilityRole="switch" accessibilityLabel="Enable notification permission" aria-checked={false} accessibilityState={{ checked: false, disabled: access.busy || access.access === 'checking' }} disabled={access.busy || access.access === 'checking'} onPress={() => void access.request()} style={N.switch}><View style={N.switchKnob} /></Pressable></View></View>}
      {!!access.notice && <View style={N.feedback}><Label accessibilityLiveRegion="polite" style={N.feedbackText}>{access.notice}</Label><Pressable accessibilityRole="button" accessibilityLabel="Open notification settings" onPress={() => void access.openSettings()} style={N.settings}><Label>{Platform.OS === 'web' ? 'How to allow notifications' : 'Open Settings'}</Label></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Retry notification permission" onPress={() => void access.request()} disabled={access.busy} style={N.settings}><Label>Try Again</Label></Pressable></View>}
      {!!access.error && <View style={N.feedback}><Label accessibilityRole="alert" style={N.error}>{access.error}</Label><Pressable accessibilityRole="button" accessibilityLabel={access.errorAction === 'request' ? 'Retry notification permission' : 'Retry notification preferences'} onPress={() => void access.retryError()} style={N.settings}><Label>Try Again</Label></Pressable></View>}
      {songs.length ? <View style={N.activity}><Label style={N.activityLabel}>Activity on this device</Label>{songs.map(song => { const read = access.preferences.readIds.includes(song.id); return <Pressable key={song.id} accessibilityRole="button" accessibilityLabel={`Open saved song ${song.title}`} onPress={() => { void access.markRead(song.id); onOpenSong(song); }} style={[N.activityRow, !read && { backgroundColor: C.field }]}><Image source={song.cover || require('../assets/demo-avatar.png')} style={N.cover} /><View style={{ flex: 1 }}><Label style={{ fontFamily: read ? 'RobotoRegular' : 'RobotoMedium' }}>{song.title}</Label><Label style={N.activityCaption}>Saved local example · {read ? 'Read' : 'New'}</Label></View><Icon name="chevron-right" color={C.secondary} /></Pressable>; })}</View> : hooks ? <View style={N.hooksEmpty}><Label style={N.hooksTitle}>It's quiet in here</Label><Label style={N.hooksSubtitle}>Create a song to get discovered</Label><Pressable accessibilityRole="button" accessibilityLabel="Create your first song" onPress={onCreate} style={N.hooksCreate}><Icon name="music-note" color={C.surface} size={24} /><Label style={{ color: C.surface, fontSize: 14 }}>Create your first song</Label></Pressable></View> : <View style={N.empty}><Image source={require('../assets/notifications-empty.png')} style={N.art} resizeMode="contain" /><Label style={N.emptyTitle}>No notifications to show</Label><Label style={N.emptySubtitle}>You're all up to date!</Label></View>}
      {!hooks && (access.preferences.dismissed || access.access === 'granted') && <View style={[N.footer, !songs.length && { position: 'absolute', bottom: 0, left: 0, right: 0 }]}><Label style={N.local}>{access.access === 'granted' ? 'Notification permission allowed · Activity stays in this local demo.' : 'Activity stays in this local demo.'}</Label><Pressable accessibilityRole="button" accessibilityLabel="Notification preferences" onPress={() => access.access === 'granted' ? void access.openSettings() : void access.showBanner()} style={N.settings}><Label style={N.activityCaption}>Notification preferences</Label></Pressable></View>}
    </ScrollView>
  </View></ThemedSurface>;
}
const styles = (C: ThemeColors) => StyleSheet.create({ hooksEmpty: { position: 'absolute', top: Platform.OS === 'web' ? '46%' : '47.25%', left: 16, right: 16, alignItems: 'center' }, hooksTitle: { fontSize: 18, lineHeight: 24, fontFamily: 'RobotoBold' }, hooksSubtitle: { fontSize: 14, lineHeight: 20, color: C.secondary, marginTop: 4 }, hooksCreate: { height: 40, borderRadius: 99, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.ink, marginTop: 16 }, page: { flex: 1, backgroundColor: C.surface }, header: { height: 64, alignItems: 'center', justifyContent: 'center' }, back: { position: 'absolute', left: 20, width: 40, height: 40, borderRadius: 99, backgroundColor: C.field }, title: { fontSize: 18, lineHeight: 24, fontFamily: 'RobotoRegular' }, content: { flexGrow: 1, paddingBottom: 16 }, banner: { marginHorizontal: 16, borderRadius: 16, padding: 16, backgroundColor: C.toolbar }, bannerHeading: { flexDirection: 'row', alignItems: 'center', gap: 12 }, bannerTitle: { flex: 1, fontSize: 14, lineHeight: 20, fontFamily: 'RobotoBold' }, close: { width: 24, height: 28 }, bannerBody: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 8 }, description: { flex: 1, fontSize: 14, lineHeight: 20, color: C.secondary }, switch: { width: 52, height: 32, borderRadius: 99, borderWidth: 2, borderColor: '#85848C', backgroundColor: '#FFFFFF', justifyContent: 'center', padding: 5 }, switchKnob: { width: 16, height: 16, backgroundColor: '#85848C', borderRadius: 99 }, empty: { flex: 1, minHeight: 300, alignItems: 'center', justifyContent: 'center', paddingTop: 45, paddingBottom: 10 }, art: { width: 224, height: 160, marginBottom: -8, transform: [{ translateY: 12 }] }, emptyTitle: { fontSize: 28, lineHeight: 38, textAlign: 'center', paddingHorizontal: 12 }, emptySubtitle: { marginTop: 4, fontSize: 16, lineHeight: 24, color: C.secondary, textAlign: 'center' }, feedback: { marginHorizontal: 16, marginTop: 12, gap: 8 }, feedbackText: { fontSize: 13, lineHeight: 20, color: C.secondary }, settings: { minHeight: 40, justifyContent: 'center', alignItems: 'center', alignSelf: 'center', paddingHorizontal: 16 }, error: { fontSize: 13, color: '#B52B19' }, activity: { padding: 16, gap: 8 }, activityLabel: { marginBottom: 8, fontSize: 14, color: C.secondary }, activityRow: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, minHeight: 80, borderRadius: 12 }, cover: { width: 48, height: 48, borderRadius: 8 }, activityCaption: { fontSize: 12, lineHeight: 18, color: C.secondary }, footer: { paddingHorizontal: 16, paddingTop: 12 }, local: { fontSize: 11, lineHeight: 17, textAlign: 'center', color: C.secondary } });
