import { ProfilePickerSession } from './profilePickerSession';
import { SettingsFlow } from './SettingsFlow';
import { ThemeColors, ThemedSurface, LightSurface, useTheme } from './Theme';
import React, { useRef, useState } from 'react';
import { Image, Platform, Pressable, ScrollView, Share, StyleSheet, Switch, View } from 'react-native';
import * as Clipboard from 'expo-clipboard';
import * as Linking from 'expo-linking';
import { LinearGradient } from 'expo-linear-gradient';
import { SubscriptionFlow } from './SubscriptionFlow';
import { useDemoEntitlements } from './useDemoEntitlements';
import { ProfileEditor } from './ProfileEditor';
import { ProfileCompletion } from './ProfileCompletion';
import { socialFields, socialURL } from './profileData';
import { ExampleCreator, encodeSharedProfile, exampleCreators } from './creatorData';
import { CreatorProfile } from './CreatorProfile';
import { PublicVoice } from './voiceData';
import { useOwnVoices } from './useOwnVoices';
import { AudioTrack } from './audioData';
import { useLibrary } from './useLibrary';
import { useLibraryPlayback } from './useLibraryPlayback';
import { useLocalProfile } from './useLocalProfile';
import { SongRow } from './SongRow';
import { AudioConfirm } from './Audio';
import { C, Icon, IconButton, Label, Sheet } from './ui';

export function Profile({ recovery, onRecoveryClosed, account, entitlements, library, player, onCreate, onSongOptions, onNotifications, onOpenPlayer, onVoice, ownVoices }: { recovery?: ProfilePickerSession | null; onRecoveryClosed?: () => void; ownVoices: ReturnType<typeof useOwnVoices>; account: ReturnType<typeof useLocalProfile>; entitlements: ReturnType<typeof useDemoEntitlements>; library: ReturnType<typeof useLibrary>; player: ReturnType<typeof useLibraryPlayback>; onCreate: () => void; onSongOptions: (song: AudioTrack) => void; onNotifications: () => void; onOpenPlayer: () => void; onVoice: (voice: PublicVoice) => void }) {
  const theme = useTheme(); const C = theme.colors; const P = styles(C, theme.dark);
  const [editOrigin, setEditOrigin] = useState<'settings' | null>(recovery?.origin === 'settings' ? 'settings' : null);
  const [subscriptionOrigin, setSubscriptionOrigin] = useState<'settings' | null>(null);
  const [panel, setPanel] = useState<'edit' | 'settings' | 'about' | 'downloads' | 'plans' | 'share' | 'completion' | null>(recovery ? recovery.screen === 'setup' ? 'completion' : recovery.origin === 'settings' ? 'settings' : 'edit' : null);
  const [linkError, setLinkError] = useState('');
  const [shareNotice, setShareNotice] = useState('');
  const [shareBusy, setShareBusy] = useState(false);
  const [deleting, setDeleting] = useState<AudioTrack | null>(null);
  const [creator, setCreator] = useState<ExampleCreator | null>(null);
  const [scrolled, setScrolled] = useState(false);
  const scroll = useRef<ScrollView>(null);
  const scrollOffset = useRef(0);
  const profile = account.profile;
  const avatar = profile.avatarUri ? { uri: profile.avatarUri } : require('../assets/demo-avatar.png');
  const recommendations = exampleCreators.filter(item => !profile.dismissedCreatorIds?.includes(item.id));
  const edit = () => { setEditOrigin(panel === 'settings' ? 'settings' : null); setPanel('edit'); };
  const follow = (id: string) => account.update(current => ({ followedCreatorIds: current.followedCreatorIds?.includes(id) ? current.followedCreatorIds.filter(value => value !== id) : [...(current.followedCreatorIds || []), id] }));
  const share = async (copy = false) => {
    if (shareBusy) return;
    setShareBusy(true); setShareNotice('');
    try {
      const url = Linking.createURL('', { queryParams: { profile: encodeSharedProfile(profile) } });
      if (copy) { await Clipboard.setStringAsync(url); setShareNotice('Link copied'); }
      else if (Platform.OS === 'web') setPanel('share');
      else await Share.share({ title: 'Share Profile', message: `${profile.name} · Local demo profile\n${url}`, ...(Platform.OS === 'ios' ? { url } : {}) });
    } catch (error) { if (!(error instanceof Error && error.name === 'AbortError')) { setShareNotice('Sharing could not open. Try Copy Link instead.'); setPanel('share'); } }
    finally { setShareBusy(false); }
  };
  if (creator) return <CreatorProfile onVoice={onVoice} key={creator.id} creator={creator} backLabel="Back to Profile" account={account} player={player} onClose={() => setCreator(null)} onSongOptions={onSongOptions} onOpenPlayer={onOpenPlayer} />;
  return <ThemedSurface><View style={P.page}>
    <ScrollView ref={scroll} testID="own-profile-scroll" showsVerticalScrollIndicator={false} scrollEventThrottle={32} onScroll={event => { scrollOffset.current = event.nativeEvent.contentOffset.y; setScrolled(scrollOffset.current > 120); }} onContentSizeChange={() => scroll.current?.scrollTo({ y: scrollOffset.current, animated: false })} contentContainerStyle={{ paddingBottom: 20 }}>
      <View style={P.hero}><Image accessibilityLabel="Profile cover" source={profile.coverUri ? { uri: profile.coverUri } : require('../assets/creator-cover.png')} style={P.heroImage} resizeMode="cover" /><LinearGradient pointerEvents="none" colors={theme.dark ? ['#10101200', '#10101288', C.surface] : ['#F8F5F000', C.surface]} locations={theme.dark ? [0, 0.4, 1] : [0, 1]} style={[P.fade, theme.dark && { height: 268 }]} /><View style={P.identity}><Image accessibilityLabel="Profile photo" source={avatar} style={P.avatar} /><View style={{ flex: 1 }}><Label numberOfLines={2} style={P.name}>{profile.name}</Label><Label style={P.handle}>@{profile.handle || 'm620-demo'}</Label></View><Pressable accessibilityRole="button" accessibilityLabel="Edit profile" onPress={edit} style={[P.edit, P.heroEdit]}><View accessibilityLabel="Edit" style={{ width: 24, height: 24, marginTop: -2 }}><Icon name="pencil" size={24} /></View><Label style={[P.actionText, { fontSize: 12, lineHeight: 15 }]}>Edit</Label></Pressable></View></View>
      {profile.bio !== 'Making room for a little more music.' && !!profile.bio && <Label style={P.bio}>{profile.bio}</Label>}
      {!!socialFields.filter(field => !!profile.links?.[field.key]).length && <View style={P.socials}>{socialFields.filter(field => !!profile.links?.[field.key]).map(field => <IconButton key={field.key} name={field.icon} label={`Open profile ${field.label}`} onPress={() => { const url = socialURL(field.key, profile.links![field.key]!); if (url) void Linking.openURL(url).catch(() => setLinkError('This link could not be opened.')); }} />)}</View>}
      {!!linkError && <Label accessibilityRole="alert" style={P.error}>{linkError}</Label>}
      <View style={P.completion}><Label style={P.sectionTitle}>Complete Your Profile</Label><Label style={[P.caption, { marginTop: -2 }]}>Step {Math.min(profile.completionStep || 0, 1) + 1} of 4</Label><Pressable accessibilityRole="button" accessibilityLabel="Complete your profile" onPress={() => setPanel('completion')} style={P.completionCard}><View style={{ flex: 1 }}><Label style={P.cardTitle}>{profile.completionStep ? 'Add a profile picture' : 'Add your name'}</Label><Label style={[P.caption, { letterSpacing: -0.15, marginTop: -2.7 }]}>{profile.completionStep ? 'An image that feels like you' : "Let people know who's making the music"}</Label></View><Icon name="chevron-right" color={C.muted} size={28} /></Pressable></View>
      <View style={P.sectionHeader}><Label style={P.sectionTitle}>Creators to Follow</Label><Pressable accessibilityRole="button" accessibilityLabel={profile.hiddenRecommendations ? 'Show recommended creators' : 'Hide recommended creators'} disabled={!account.ready} onPress={() => account.update(current => ({ hiddenRecommendations: !current.hiddenRecommendations }))} style={P.hideTarget}><Label style={[P.caption, { letterSpacing: 0.45 }]}>{profile.hiddenRecommendations ? 'Show' : 'Hide'}</Label></Pressable></View>
      {!profile.hiddenRecommendations && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={P.recommendations}>{recommendations.map(item => { const followed = !!profile.followedCreatorIds?.includes(item.id); return <View key={item.id} style={P.creatorCard}><Pressable accessibilityRole="button" accessibilityLabel={`Open recommended creator ${item.name}`} onPress={() => setCreator(item)} style={P.creatorIdentity}><Image source={item.avatar} style={P.creatorAvatar} /><Label numberOfLines={1} style={P.creatorName}>{item.name}</Label><Label style={[P.creatorCaption, { fontSize: 12.5, lineHeight: 16 }]}>Popular</Label></Pressable><IconButton name="close" size={18} label={`Not interested in ${item.name}`} disabled={!account.ready} onPress={() => account.update(current => ({ dismissedCreatorIds: [...new Set([...(current.dismissedCreatorIds || []), item.id])] }))} style={P.dismiss} /><Pressable accessibilityRole="button" accessibilityLabel={followed ? `Unfollow recommended ${item.name} locally` : `Follow recommended ${item.name} locally`} aria-pressed={followed} accessibilityState={{ selected: followed, disabled: !account.ready }} disabled={!account.ready} onPress={() => follow(item.id)} style={P.follow}><Icon name={followed ? 'account-check' : 'account-plus'} size={24} /></Pressable></View>; })}{!recommendations.length && <View style={P.recommendationEmpty}><Label style={P.caption}>No more recommendations</Label><Pressable accessibilityRole="button" accessibilityLabel="Restore recommended creators" onPress={() => account.update({ dismissedCreatorIds: [] })} style={P.edit}><Label>Show again</Label></Pressable></View>}</ScrollView>}
      <Label style={[P.sectionTitle, P.songsHeading]}>Songs</Label>
      {library.songs.length ? library.songs.map(track => <View key={track.id}><SongRow track={track} playing={player.track?.id === track.id && player.status.playing} onPress={() => void player.playTrack(track, library.songs, 'profile')} onOptions={() => onSongOptions(track)} /><Pressable accessibilityRole="button" accessibilityLabel={`Delete local song ${track.title}`} onPress={() => setDeleting(track)} style={P.delete}><Label style={{ fontSize: 12, color: C.muted }}>Delete local song</Label></Pressable></View>) : <View style={P.empty}><View accessible={false} importantForAccessibility="no-hide-descendants" pointerEvents="none" style={StyleSheet.absoluteFill}>{[0, 1, 2].map(row => <View key={row} style={P.ghostRow}><View style={P.ghostCover} /><View style={{ gap: 8 }}><View style={[P.ghostLine, { width: 144 }]} /><View style={[P.ghostLine, { width: 80 }]} /></View></View>)}</View><Label style={P.emptyLabel}>No songs added yet</Label><Pressable accessibilityRole="button" accessibilityLabel="Create your first song" onPress={onCreate} style={P.create}><Icon name="music-note" color={C.surface} size={24} /><Label style={P.createLabel}>Create your first song</Label></Pressable></View>}
      {!!ownVoices.voices.length && <><Label style={[P.sectionTitle, P.songsHeading]}>Voices</Label><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ paddingHorizontal: 16, gap: 4 }}>{ownVoices.voices.map(voice => <Pressable key={voice.id} accessibilityRole="button" accessibilityLabel={`Open Voice ${voice.name}`} onPress={() => onVoice(voice)} style={{ width: 134, alignItems: 'center', paddingBottom: 8 }}><Image source={require('../assets/voice-public-hero.png')} style={{ width: 112, height: 112 }} accessible={false} /><Label numberOfLines={1} style={{ fontSize: 14, lineHeight: 20, marginTop: 8, maxWidth: 126 }}>{voice.name}</Label></Pressable>)}</ScrollView></>}
      {!!ownVoices.error && <View><Label accessibilityRole="alert" style={P.error}>{ownVoices.error}</Label><Pressable accessibilityRole="button" accessibilityLabel="Retry saved Voices" onPress={ownVoices.retry} style={P.edit}><Label>Retry</Label></Pressable></View>}
      <View style={P.footerIdentity}><Image source={avatar} style={P.footerAvatar} /><Label numberOfLines={2} style={P.footerName}>{profile.name}</Label><Pressable accessibilityRole="button" accessibilityLabel="Edit profile from footer" onPress={edit} style={P.edit}><Icon name="pencil" /><Label style={P.actionText}>Edit</Label></Pressable></View>
      <Label style={P.local}>Local demo profile · Follows and songs stay on this device</Label>
      {!!library.error && <View><Label accessibilityRole="alert" style={P.error}>{library.error}</Label>{!!library.data.removedMedia?.length && <Pressable accessibilityRole="button" accessibilityLabel="Retry media cleanup" onPress={() => void library.retryCleanup()} style={P.edit}><Label>Retry media cleanup</Label></Pressable>}</View>}
      {!!account.error && <Label accessibilityLiveRegion="polite" style={P.error}>{account.error}</Label>}
    </ScrollView>
    <View pointerEvents="box-none" style={[P.header, scrolled && { backgroundColor: C.field }]}><Pressable accessibilityRole="button" accessibilityLabel="Upgrade profile" onPress={() => { setSubscriptionOrigin(null); setPanel('plans'); }} style={P.upgrade}><Icon name="crown-outline" size={24} /><Label style={P.upgradeText}>Upgrade</Label></Pressable><View style={{ flex: 1 }} /><IconButton name="share-variant-outline" label="Share profile" disabled={shareBusy || !account.ready} onPress={() => void share()} style={P.round} /><IconButton name="bell" label="Profile notifications" onPress={onNotifications} style={P.round} /><IconButton name="cog" label="Profile settings" onPress={() => { setSubscriptionOrigin('settings'); setPanel('settings'); }} style={P.round} /></View>
    {panel === 'completion' && <LightSurface><ProfileCompletion recovery={recovery?.screen === 'setup' ? recovery : null} account={account} onClose={() => { onRecoveryClosed?.(); setPanel(null); }} onContinue={() => { onRecoveryClosed?.(); setEditOrigin(null); setPanel('edit'); }} /></LightSurface>}
    {panel === 'share' && <Sheet compact onClose={() => setPanel(null)}><View style={P.panel}><Label style={P.panelTitle}>Share Profile</Label><Label style={P.caption}>This link includes your display name, username and bio. Photos and songs stay on this device.</Label><Pressable accessibilityRole="button" accessibilityLabel="Copy profile link" disabled={shareBusy} onPress={() => void share(true)} style={P.setting}><Icon name="link-variant" /><Label>Copy Link</Label></Pressable><Label accessibilityLiveRegion="polite" style={P.caption}>{shareNotice}</Label></View></Sheet>}
    {(panel === 'downloads' || panel === 'plans') && <LightSurface><SubscriptionFlow initialRoute={panel} entitlements={entitlements} onClose={() => setPanel(subscriptionOrigin)} /></LightSurface>}
    {panel === 'edit' && <LightSurface><ProfileEditor recovery={recovery?.screen === 'editor' ? recovery : null} origin={editOrigin || 'profile'} account={account} onClose={() => { onRecoveryClosed?.(); setPanel(editOrigin); }} /></LightSurface>}
    {panel === 'settings' && <SettingsFlow recovery={recovery?.origin === 'settings' ? recovery : null} onRecoveryClosed={onRecoveryClosed} account={account} entitlements={entitlements} onClose={() => setPanel(null)} />}
    {deleting && <AudioConfirm destructive title="Delete local song?" description="This removes the saved example and its playlist memberships from this device." confirm="Delete song" cancel="Cancel" onCancel={() => setDeleting(null)} onConfirm={() => { if (player.track?.id === deleting.id) player.clear(); void library.deleteSong(deleting.id).then(removed => { if (removed) setDeleting(null); }); }} />}
  </View></ThemedSurface>;
}
const styles = (C: ThemeColors, dark: boolean) => StyleSheet.create({
  page: { flex: 1, backgroundColor: C.surface }, hero: { height: 268 }, heroImage: { position: 'absolute', width: '100%', height: '100%' }, fade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 52 },
  header: { position: 'absolute', left: 0, right: 0, top: -5, height: 76, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 12 }, round: { width: 40, height: 40, borderRadius: 99, backgroundColor: dark ? '#28282ACC' : '#FFFFFFB8' }, upgrade: { height: 40, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 16, borderRadius: 99, backgroundColor: dark ? '#28282ACC' : '#FFFFFFB8' }, upgradeText: { fontSize: 14, lineHeight: 20 },
  identity: { position: 'absolute', bottom: 16, left: 16, right: 16, flexDirection: 'row', alignItems: 'center', gap: 8 }, avatar: { width: 76, height: 76, borderRadius: 99 }, name: { fontSize: 28, lineHeight: 34, fontFamily: 'RobotoBold' }, handle: { fontSize: 14, lineHeight: 22 }, bio: { fontSize: 14, lineHeight: 21, marginHorizontal: 16, marginTop: 12 }, socials: { flexDirection: 'row', marginHorizontal: 16, gap: 8, marginTop: 8 },
  caption: { fontSize: 14, lineHeight: 20, letterSpacing: -0.3, color: C.muted }, hideTarget: { height: 48, width: 48, alignItems: 'center', justifyContent: 'center', marginRight: -9 },
  edit: { minHeight: 40, paddingHorizontal: 16, flexDirection: 'row', gap: 4, borderRadius: 99, backgroundColor: C.control, justifyContent: 'center', alignItems: 'center' }, heroEdit: { backgroundColor: dark ? '#28282AAA' : '#E5D0CA88' }, actionText: { fontSize: 14, lineHeight: 20 },
  completion: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 12 }, sectionTitle: { fontSize: 18, lineHeight: 24, letterSpacing: 0.15, fontFamily: 'RobotoRegular' }, completionCard: { minHeight: 72, marginTop: 10, paddingHorizontal: 20, paddingTop: 18.5, paddingBottom: 13.5, flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 16, backgroundColor: C.field }, cardTitle: { fontSize: 16, lineHeight: 22, letterSpacing: 0.18, marginBottom: 4 }, sectionHeader: { marginHorizontal: 16, marginTop: 2, marginBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, textButton: { minHeight: 32, paddingLeft: 12, justifyContent: 'center' },
  recommendations: { paddingHorizontal: 16, gap: 8 }, creatorCard: { width: 140, height: 180, borderRadius: 12, backgroundColor: C.field, padding: 8 }, creatorIdentity: { alignItems: 'center', paddingTop: 0, flex: 1 }, creatorAvatar: { width: 64, height: 64, borderRadius: 99, marginBottom: 6 }, creatorName: { fontSize: 14, lineHeight: 20 }, creatorCaption: { fontSize: 12, lineHeight: 18, color: C.muted }, dismiss: { position: 'absolute', right: 2, top: 2, width: 28, height: 28 }, follow: { height: 40, borderRadius: 99, backgroundColor: C.control, alignItems: 'center', justifyContent: 'center' }, recommendationEmpty: { minHeight: 140, gap: 16, justifyContent: 'center' },
  songsHeading: { marginHorizontal: 16, marginTop: 9, marginBottom: 8 }, empty: { height: 188, marginHorizontal: 16, alignItems: 'center', justifyContent: 'center', gap: 16 }, ghostRow: { flexDirection: 'row', gap: 12, height: 64, alignItems: 'center' }, ghostCover: { width: 56, height: 56, borderRadius: 12, backgroundColor: C.field, borderWidth: 1, borderColor: C.divider }, ghostLine: { height: 10, backgroundColor: C.field, borderRadius: 99 }, emptyLabel: { fontSize: 14, lineHeight: 20 }, create: { minHeight: 40, paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: C.ink, borderRadius: 99 }, createLabel: { fontSize: 14, color: C.surface, lineHeight: 20 }, footerIdentity: { minHeight: 104, marginTop: 20, marginHorizontal: 16, padding: 20, borderRadius: 16, backgroundColor: C.field, flexDirection: 'row', alignItems: 'center', gap: 8 }, footerAvatar: { width: 40, height: 40, borderRadius: 99 }, footerName: { flex: 1, fontSize: 18, lineHeight: 24, fontFamily: 'RobotoBold' },
  local: { margin: 16, textAlign: 'center', color: C.muted, fontSize: 11, lineHeight: 16 }, error: { color: '#B52B19', padding: 16 }, panel: { padding: 20, gap: 14 }, panelTitle: { fontSize: 24, lineHeight: 30, fontFamily: 'RobotoMedium' }, setting: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 16, borderBottomWidth: 1, borderBottomColor: C.border }, delete: { alignSelf: 'flex-end', paddingHorizontal: 20, minHeight: 36, justifyContent: 'center' },
});
