import { ThemeColors, useSurfaceColors } from './Theme';
import React, { useRef } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { AudioTrack, exampleTracks } from './audioData';
import { useLibrary } from './useLibrary';
import { useLibraryPlayback } from './useLibraryPlayback';
import { SongRow } from './SongRow';
import { C, Icon, Label } from './ui';
export function SearchDiscover({ library, player, onSongOptions, onProfile, onInspiration, onOpenPlayer, onBrowse, scrollOffsets, commentCounts }: {
    library: ReturnType<typeof useLibrary>;
    player: ReturnType<typeof useLibraryPlayback>;
    onSongOptions: (song: AudioTrack) => void;
    onProfile: () => void;
    commentCounts: Record<string, number>;
    onInspiration: (kind: 'photo' | 'record') => void;
    onOpenPlayer: () => void;
    onBrowse: () => void;
    scrollOffsets: React.MutableRefObject<Record<string, number>>;
}) {
    const C = useSurfaceColors();
    const D = styles(C);
    const scroll = useRef<ScrollView>(null);
    const play = (track: AudioTrack) => void player.playTrack(track, exampleTracks, 'search-featured');
    const section = (title: string) => <View style={D.headingRow}><Label style={D.heading}>{title}</Label><Pressable accessibilityRole="button" accessibilityLabel={`Browse ${title}`} onPress={onBrowse} style={D.more}><Label style={D.moreText}>More</Label><View style={{ marginRight: -4 }}><Icon name="chevron-right" size={18} color={C.secondary}/></View></Pressable></View>;
    return <ScrollView ref={scroll} onContentSizeChange={() => scroll.current?.scrollTo({ y: scrollOffsets.current.discover || 0, animated: false })} onScroll={event => { scrollOffsets.current.discover = event.nativeEvent.contentOffset.y; }} scrollEventThrottle={100} showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 24 }}>
    <Label style={[D.heading, { fontFamily: 'RobotoMedium', marginHorizontal: 16, marginTop: 7, marginBottom: 6 }]}>Get Inspired</Label>
    <Pressable accessibilityRole="button" accessibilityLabel="Turn a photo into a song" onPress={() => onInspiration('photo')} style={D.feature}><View style={D.featureArt}><Image source={require('../assets/morning-light-cover.png')} style={[StyleSheet.absoluteFill, { width: '100%', height: '100%' }]} resizeMode="cover"/><View style={D.camera}><Icon name="camera" color={C.white} size={24}/></View></View><View style={{ flex: 1, paddingRight: 10, marginTop: 4 }}><Label style={D.featureEyebrow}>New Feature</Label><Label style={D.featureTitle}>Turn any photo into a song</Label><Label style={D.featureDescription}>Snap a picture and fill in the blanks</Label></View></Pressable>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={D.prompts}>{[{ title: 'Wind down with a bedtime song', text: 'Record how today felt and turn it into music', image: exampleTracks[1].cover }, { title: 'Create a song from a memory', text: 'Record a thought and find your sound', image: exampleTracks[0].cover }].map(item => <Pressable key={item.title} accessibilityRole="button" accessibilityLabel={item.title} onPress={() => onInspiration('record')} style={D.prompt}><View style={D.promptArt}><Image source={item.image!} style={[StyleSheet.absoluteFill, { width: '100%', height: '100%' }]} resizeMode="cover"/><View style={D.mic}><Icon name="microphone-outline" color={C.white} size={18}/></View></View><View style={{ flex: 1 }}><Label numberOfLines={1} style={D.promptTitle}>{item.title}</Label><Label numberOfLines={1} style={D.promptDescription}>{item.text}</Label></View></Pressable>)}</ScrollView>
    {section('Best of v6')}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={D.featured}>{exampleTracks.map(track => <View key={track.id} style={D.featuredItem}><Pressable accessibilityRole="button" accessibilityLabel={`${player.track?.id === track.id && player.status.playing ? 'Pause' : 'Play'} featured ${track.title}`} onPress={() => play(track)} style={D.art}><Image source={track.cover!} style={[StyleSheet.absoluteFill, { width: '100%', height: '100%' }]} resizeMode="cover"/><View style={D.stats}><View style={{ flexDirection: 'row', gap: 4 }}><View style={D.stat}><Icon name="play" color={C.white} size={16}/><Label style={D.statText}>{track.plays || 0}</Label></View><View style={D.stat}><Icon name="thumb-up" color={C.white} size={16}/><Label style={D.statText}>{library.data.likedIds?.includes(track.id) ? 1 : 0}</Label></View></View><View style={[D.stat, { alignSelf: 'flex-start' }]}><Icon name="comment-text" color={C.white} size={16}/><Label style={D.statText}>{commentCounts[track.id] || 0}</Label></View></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Open featured ${track.title} player`} onPress={() => { if (player.track?.id !== track.id)
        void player.start(track, exampleTracks, 'search-featured'); onOpenPlayer(); }}><Label numberOfLines={1} style={D.trackTitle}>{track.title}</Label></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`View ${track.title} creator`} onPress={onProfile}><Label style={D.creator}>M620</Label></Pressable></View>)}</ScrollView>
    {section('Staff Picks')}
    {exampleTracks.map(track => <SongRow variant="search" key={track.id} track={track} playing={player.track?.id === track.id && player.status.playing} onPress={() => play(track)} onOptions={() => onSongOptions(track)}/>)}
    <Label style={D.disclosure}>Local example music · Original recordings</Label>
  </ScrollView>;
}
const styles = (C: ThemeColors) => StyleSheet.create({ heading: { fontSize: 18, lineHeight: 24, fontFamily: 'RobotoRegular' }, headingRow: { marginHorizontal: 16, marginTop: 18, marginBottom: 12, height: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, more: { flexDirection: 'row', alignItems: 'center', gap: 0, paddingLeft: 14, minHeight: 48 }, moreText: { fontSize: 14, color: C.secondary }, feature: { marginHorizontal: 16, minHeight: 114, padding: 2, borderRadius: 24, backgroundColor: C.field, flexDirection: 'row', alignItems: 'center', gap: 16 }, featureArt: { width: 110, height: 110, borderRadius: 24, overflow: 'hidden', borderWidth: 2, borderColor: C.primary }, camera: { position: 'absolute', right: 5, bottom: 5, backgroundColor: '#00000055', borderRadius: 12, padding: 6 }, featureEyebrow: { fontSize: 14, lineHeight: 17, color: C.primary, fontFamily: 'RobotoMedium' }, featureTitle: { fontSize: 18, lineHeight: 22, fontFamily: 'RobotoRegular' }, featureDescription: { fontSize: 14, lineHeight: 17, letterSpacing: -0.16, color: C.secondary }, prompts: { paddingHorizontal: 16, gap: 12, paddingTop: 15, paddingBottom: 10 }, prompt: { width: 280, height: 64, borderRadius: 16, backgroundColor: C.field, padding: 8, flexDirection: 'row', alignItems: 'center', gap: 12 }, promptArt: { width: 44, height: 44, borderRadius: 10, overflow: 'hidden' }, mic: { position: 'absolute', right: 0, bottom: 0, backgroundColor: '#5F5F66', borderRadius: 99, padding: 3 }, promptTitle: { fontSize: 14, lineHeight: 17 }, promptDescription: { fontSize: 12, lineHeight: 17, color: C.secondary }, featured: { paddingHorizontal: 16, gap: 12, paddingBottom: 1 }, featuredItem: { width: 153 }, art: { width: 153, height: 153, borderRadius: 12, overflow: 'hidden' }, stats: { position: 'absolute', bottom: 3, left: 3, gap: 4 }, stat: { backgroundColor: '#00000088', flexDirection: 'row', alignItems: 'center', borderRadius: 4, gap: 2, paddingHorizontal: 4, paddingVertical: 2 }, statText: { fontSize: 12, color: C.white, fontFamily: 'RobotoMedium' }, trackTitle: { fontSize: 16, lineHeight: 20, marginTop: 8 }, creator: { fontSize: 14, lineHeight: 18, color: C.muted, marginTop: 2 }, disclosure: { fontSize: 10, color: C.muted, lineHeight: 16, margin: 20, textAlign: 'center' } });
